"""empty message

Revision ID: 0125601f3924
Revises: e2e3f6dd3594
Create Date: 2025-10-11 16:59:04.101692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0125601f3924'
down_revision: Union[str, Sequence[str], None] = 'e2e3f6dd3594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('free_shipping_threshold')

    # ### end Alembic commands ###
