"""empty message

Revision ID: 08d38e97306d
Revises: 195532e0e46b
Create Date: 2025-08-28 01:27:45.983484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '08d38e97306d'
down_revision: Union[str, Sequence[str], None] = '195532e0e46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchaseitemmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_variant', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchaseitemmodel', schema=None) as batch_op:
        batch_op.drop_column('selected_variant')

    # ### end Alembic commands ###
