"""empty message

Revision ID: 0b5a709aeb22
Revises: 4c2e76874867
Create Date: 2025-07-04 16:38:43.907678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0b5a709aeb22'
down_revision: Union[str, Sequence[str], None] = '4c2e76874867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
