"""empty message

Revision ID: 155042d4121b
Revises: acd32698222e
Create Date: 2025-09-09 12:54:49.760277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '155042d4121b'
down_revision: Union[str, Sequence[str], None] = 'acd32698222e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wompi_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('wompi_events', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchasemodel_wompi_transaction_id'), ['wompi_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasemodel_wompi_transaction_id'))
        batch_op.drop_column('wompi_events')
        batch_op.drop_column('wompi_transaction_id')

    # ### end Alembic commands ###
