"""empty message

Revision ID: 20a2c0579e80
Revises: e2e3f6dd3594
Create Date: 2025-10-17 14:02:56.985744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '20a2c0579e80'
down_revision: Union[str, Sequence[str], None] = 'e2e3f6dd3594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('card_bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('title_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('price_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('price_color')
        batch_op.drop_column('title_color')
        batch_op.drop_column('card_bg_color')
        batch_op.drop_column('free_shipping_threshold')

    # ### end Alembic commands ###
