"""empty message

Revision ID: 2711c053d565
Revises: 632d0f04f0cc
Create Date: 2025-08-23 18:07:44.737883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2711c053d565'
down_revision: Union[str, Sequence[str], None] = '632d0f04f0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('free_shipping_threshold')

    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_applied', sa.Float(), nullable=True))

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('free_shipping_threshold')

    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('shipping_applied')

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
