"""empty message

Revision ID: 31032213eea5
Revises: 2711c053d565
Create Date: 2025-08-23 22:10:44.975801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '31032213eea5'
down_revision: Union[str, Sequence[str], None] = '2711c053d565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moda_completa_eligible', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('free_shipping_threshold')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('is_moda_completa_eligible')

    # ### end Alembic commands ###
