"""empty message

Revision ID: 339d114463e0
Revises: 48bbdd8a086f
Create Date: 2025-09-21 21:54:03.714491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339d114463e0'
down_revision: Union[str, Sequence[str], None] = '48bbdd8a086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogpostmodel_variants_gin'), postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogpostmodel_variants_gin'), ['variants'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
