"""empty message

Revision ID: 37a22d018f3f
Revises: abf114c433c6
Create Date: 2025-07-08 00:17:05.238279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '37a22d018f3f'
down_revision: Union[str, Sequence[str], None] = 'abf114c433c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), server_default=sa.text('0.0'), nullable=False))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.alter_column('publish_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.alter_column('publish_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('images')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
