"""empty message

Revision ID: 3a640a8701ca
Revises: 0b5a709aeb22
Create Date: 2025-07-04 22:29:56.493673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3a640a8701ca'
down_revision: Union[str, Sequence[str], None] = '0b5a709aeb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postimagemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blogpostmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('postimagemodel')
    # ### end Alembic commands ###
