"""empty message

Revision ID: 4662324fad52
Revises: 7126f215e915
Create Date: 2025-10-17 15:03:26.112699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4662324fad52'
down_revision: Union[str, Sequence[str], None] = '7126f215e915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('card_bg_color')
        batch_op.drop_column('title_color')
        batch_op.drop_column('price_color')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_color', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title_color', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('card_bg_color', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
