"""empty message

Revision ID: 47959850c2f8
Revises: 7d19ed88fb7a
Create Date: 2025-09-29 19:39:30.478226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '47959850c2f8'
down_revision: Union[str, Sequence[str], None] = '7d19ed88fb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_shipping_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('actual_shipping_cost')

    # ### end Alembic commands ###
