"""empty message

Revision ID: 48e00a539c9b
Revises: c27da85ca4cb
Create Date: 2025-07-19 19:34:33.218627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '48e00a539c9b'
down_revision: Union[str, Sequence[str], None] = 'c27da85ca4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blogpostmodel.id'], ),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentvotemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=True),
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['commentmodel.id'], ),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentvotemodel')
    op.drop_table('commentmodel')
    # ### end Alembic commands ###
