"""empty message

Revision ID: 48edf551e18e
Revises: 339d114463e0
Create Date: 2025-09-29 22:00:11.605987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '48edf551e18e'
down_revision: Union[str, Sequence[str], None] = '339d114463e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit', sa.Float(), nullable=True))

    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_shipping_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('actual_shipping_cost')

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('profit')

    # ### end Alembic commands ###
