"""empty message

Revision ID: 5fee04184ec9
Revises: 0c62bf795e49
Create Date: 2025-10-09 15:32:11.917621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5fee04184ec9'
down_revision: Union[str, Sequence[str], None] = '0c62bf795e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonymous_customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchasemodel_anonymous_customer_email'), ['anonymous_customer_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasemodel_anonymous_customer_email'))
        batch_op.drop_column('anonymous_customer_email')

    # ### end Alembic commands ###
