"""empty message

Revision ID: 632d0f04f0cc
Revises: 9498610b1ac5
Create Date: 2025-08-23 17:00:41.284571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '632d0f04f0cc'
down_revision: Union[str, Sequence[str], None] = '9498610b1ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('free_shipping_threshold', sa.Integer(), nullable=True))

    with op.batch_alter_table('shippingaddress', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippingaddress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('free_shipping_threshold')
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###
