"""empty message

Revision ID: 708ec793bcdb
Revises: aa955e48aef1
Create Date: 2025-10-18 11:38:46.468549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '708ec793bcdb'
down_revision: Union[str, Sequence[str], None] = 'aa955e48aef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('image_transform')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_transform', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_styles')

    # ### end Alembic commands ###
