"""empty message

Revision ID: 75f9c2139299
Revises: 8fec435c49ac
Create Date: 2025-08-18 13:01:56.904484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '75f9c2139299'
down_revision: Union[str, Sequence[str], None] = '8fec435c49ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedpostlink',
    sa.Column('userinfo_id', sa.Integer(), nullable=False),
    sa.Column('blogpostmodel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blogpostmodel_id'], ['blogpostmodel.id'], ),
    sa.ForeignKeyConstraint(['userinfo_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('userinfo_id', 'blogpostmodel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savedpostlink')
    # ### end Alembic commands ###
