"""empty message

Revision ID: 8600e539a996
Revises: f35f987f58cf
Create Date: 2025-09-17 19:26:18.561101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8600e539a996'
down_revision: Union[str, Sequence[str], None] = 'f35f987f58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_direct_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('is_direct_sale')

    # ### end Alembic commands ###
