"""add_2fa_fields_to_userinfo

Revision ID: 873b2cfc32a0
Revises: 48edf551e18e
Create Date: 2025-10-02 00:04:56.959405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873b2cfc32a0'
down_revision: Union[str, Sequence[str], None] = '48edf551e18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('tfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userinfo', sa.Column('tfa_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'tfa_enabled')
    op.drop_column('userinfo', 'tfa_secret')
    # ### end Alembic commands ###
