"""empty message

Revision ID: 8edf30378ddb
Revises: b9c3f662b028
Create Date: 2025-09-11 17:21:58.542146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8edf30378ddb'
down_revision: Union[str, Sequence[str], None] = 'b9c3f662b028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wompi_payment_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchasemodel_wompi_payment_link_id'), ['wompi_payment_link_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasemodel_wompi_payment_link_id'))
        batch_op.drop_column('wompi_payment_link_id')

    # ### end Alembic commands ###
