"""empty message

Revision ID: a08fd85dc1f9
Revises: 464ff5ea835c
Create Date: 2025-06-10 01:20:51.568610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a08fd85dc1f9'
down_revision: Union[str, None] = '464ff5ea835c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userinfo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['userinfo_id'], ['id'])

    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userinfo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['userinfo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userinfo_id')

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userinfo_id')

    # ### end Alembic commands ###
