"""empty message

Revision ID: a4ea00b34815
Revises: aff9254f20ab
Create Date: 2025-10-27 03:47:28.772631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a4ea00b34815'
down_revision: Union[str, Sequence[str], None] = 'aff9254f20ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_mode_appearance', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'light'"), nullable=False))
        batch_op.add_column(sa.Column('dark_mode_appearance', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'dark'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_column('dark_mode_appearance')
        batch_op.drop_column('light_mode_appearance')

    # ### end Alembic commands ###
