"""empty message

Revision ID: aa955e48aef1
Revises: 5be6a5ccf6c7
Create Date: 2025-10-18 08:11:02.516936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aa955e48aef1'
down_revision: Union[str, Sequence[str], None] = '5be6a5ccf6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_transform', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('image_styles')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_styles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('image_transform')

    # ### end Alembic commands ###
