"""empty message

Revision ID: aaeb92bb2384
Revises: 7f9a5dc7af60
Create Date: 2026-01-28 09:36:52.739782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aaeb92bb2384'
down_revision: Union[str, Sequence[str], None] = '7f9a5dc7af60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_carrier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('shipping_type', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'manual'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('shipping_type')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('shipping_carrier')

    # ### end Alembic commands ###
