"""Refactor card styles to use theme_invert

Revision ID: aff9254f20ab
Revises: df9945b16c2b
Create Date: 2025-10-26 22:56:20.271327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff9254f20ab'
down_revision: Union[str, Sequence[str], None] = 'df9945b16c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpostmodel', sa.Column('card_theme_invert', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpostmodel', 'card_theme_invert')
    # ### end Alembic commands ###
