"""empty message

Revision ID: ba7a47750ab8
Revises: 712721515b95
Create Date: 2025-09-21 15:06:45.781876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7a47750ab8'
down_revision: Union[str, Sequence[str], None] = '712721515b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogpostmodel_variants'), postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogpostmodel_variants'), ['variants'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
