"""empty message

Revision ID: bcfb574f2d5b
Revises: e75d6c2a7686
Create Date: 2025-10-08 01:42:26.718081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bcfb574f2d5b'
down_revision: Union[str, Sequence[str], None] = 'e75d6c2a7686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['last_modified_by_id'], ['id'])

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['creator_id'], ['id'])

    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userinfo', ['action_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action_by_id')

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('blogpostmodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_modified_by_id')

    # ### end Alembic commands ###
