"""empty message

Revision ID: c31d3d3bace2
Revises: 77fdaf483c31
Create Date: 2025-12-10 16:12:54.882843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c31d3d3bace2'
down_revision: Union[str, Sequence[str], None] = '77fdaf483c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key(None, 'blogpostmodel', ['blog_post_id'], ['id'])
        batch_op.create_foreign_key(None, 'commentmodel', ['comment_id'], ['id'])
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('target_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('blog_post_id')

    # ### end Alembic commands ###
