"""empty message

Revision ID: d4e8f89c9312
Revises: c6dbad945fde
Create Date: 2025-08-20 15:12:08.719169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4e8f89c9312'
down_revision: Union[str, Sequence[str], None] = 'c6dbad945fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchaseitemmodel', ['purchase_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentmodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_item_id')

    # ### end Alembic commands ###
