"""empty message

Revision ID: d846fe10e5e4
Revises: 4fcb390efaf2
Create Date: 2025-08-25 00:08:15.275749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd846fe10e5e4'
down_revision: Union[str, Sequence[str], None] = '4fcb390efaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ✨ INSTRUCCIÓN MANUAL AÑADIDA PARA ACTUALIZAR EL ENUM EN POSTGRESQL ✨
    op.execute("ALTER TYPE purchasestatus ADD VALUE 'delivered'")
    
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'online'"), nullable=False))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_confirmation_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_confirmed_delivery_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_column('user_confirmed_delivery_at')
        batch_op.drop_column('delivery_confirmation_sent_at')
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('payment_method')

    # No añadimos un downgrade para el ENUM porque es una operación compleja y riesgosa.
    # ### end Alembic commands ###