"""empty message

Revision ID: df2118d07c16
Revises: ced42742a461
Create Date: 2025-09-14 11:12:24.407927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'df2118d07c16'
down_revision: Union[str, Sequence[str], None] = 'ced42742a461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Esta parte añade las nuevas columnas y se mantiene igual.
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistecredito_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sistecredito_authorization_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sistecredito_invoice', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_authorization_code'), ['sistecredito_authorization_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_invoice'), ['sistecredito_invoice'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_transaction_id'), ['sistecredito_transaction_id'], unique=True)

    # --- INICIO DE LA CORRECCIÓN MANUAL ---
    # Estas líneas son las que faltaban. Le dicen a la base de datos
    # que acepte los nuevos valores para el estado de la compra.
    op.execute("ALTER TYPE purchasestatus ADD VALUE 'PENDING_SISTECREDITO_URL'")
    op.execute("ALTER TYPE purchasestatus ADD VALUE 'FAILED'")
    # --- FIN DE LA CORRECCIÓN MANUAL ---

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Esta parte elimina las columnas y se mantiene igual.
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_invoice'))
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_authorization_code'))
        batch_op.drop_column('sistecredito_invoice')
        batch_op.drop_column('sistecredito_authorization_code')
        batch_op.drop_column('sistecredito_transaction_id')

    # Nota: No se añade un downgrade para el ENUM porque es un proceso complejo
    # y riesgoso que podría corromper datos si los nuevos estados ya están en uso.

    # ### end Alembic commands ###