"""empty message

Revision ID: df2118d07c16
Revises: ced42742a461
Create Date: 2025-09-14 11:12:24.407927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'df2118d07c16'
down_revision: Union[str, Sequence[str], None] = 'ced42742a461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistecredito_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sistecredito_authorization_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('sistecredito_invoice', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_authorization_code'), ['sistecredito_authorization_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_invoice'), ['sistecredito_invoice'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchasemodel_sistecredito_transaction_id'), ['sistecredito_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchasemodel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_invoice'))
        batch_op.drop_index(batch_op.f('ix_purchasemodel_sistecredito_authorization_code'))
        batch_op.drop_column('sistecredito_invoice')
        batch_op.drop_column('sistecredito_authorization_code')
        batch_op.drop_column('sistecredito_transaction_id')

    # ### end Alembic commands ###
