"""empty message

Revision ID: dfedf0440819
Revises: 901a323df812
Create Date: 2025-10-06 01:52:08.940464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dfedf0440819'
down_revision: Union[str, Sequence[str], None] = '901a323df812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleadovendedorlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['userinfo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleadovendedorlink')
    # ### end Alembic commands ###
