"""empty message

Revision ID: e0af7165df1d
Revises: 0001
Create Date: 2025-08-10 19:58:19.246244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e0af7165df1d'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('ban_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userinfo', schema=None) as batch_op:
        batch_op.drop_column('ban_expires_at')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
