"""empty message

Revision ID: fba911e49d55
Revises: 75f9c2139299
Create Date: 2025-08-18 22:32:04.483947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fba911e49d55'
down_revision: Union[str, Sequence[str], None] = '75f9c2139299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('author_initial', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentmodel', schema=None) as batch_op:
        batch_op.drop_column('author_initial')
        batch_op.drop_column('author_username')

    # ### end Alembic commands ###
